# Generated by Django 4.1 on 2022-10-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveChat', '0004_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='default.JPG', upload_to='profile_pics'),
        ),
    ]
